name: Semantic PR title

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  semantic:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
